# Generated by Django 5.2.4 on 2026-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="filter_style",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="font_style",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="photography_style",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
