# Generated by Django 5.2.4 on 2026-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_remove_lead_phone_number_lead_company_lead_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
