# Generated by Django 5.2.4 on 2026-02-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="initialsetup",
            field=models.CharField(default="0", max_length=4),
        ),
    ]
