# Generated by Django 5.2.4 on 2026-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_initialsetup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="initialsetup",
            field=models.CharField(default="1", max_length=4),
        ),
    ]
