# Generated by Django 5.2.4 on 2025-09-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("appversion", models.CharField(blank=True, max_length=200, null=True)),
                ("platform", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="settings/logo/"
                    ),
                ),
                ("terms", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Settings",
                "verbose_name_plural": "App Settings",
            },
        ),
        migrations.CreateModel(
            name="AppMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("MP4", "MP4"), ("YOUTUBE", "YouTube")], max_length=10
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="settings/videos/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="settings/thumbnails/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "app_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="app_settings.appsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Media",
                "verbose_name_plural": "App Media",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
